apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgenova-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edgenova
  template:
    metadata:
      labels:
        app: edgenova
    spec:
      containers:
        - name: edgenova-container
          image: enzoluismine-dockerhub/edgenova:latest  # Substitua por sua imagem real no Docker Hub, ex: enzoluismine/edgenova:latest
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: PYTHONUNBUFFERED
              value: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: edgenova-service
spec:
  selector:
    app: edgenova
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP  # Use "LoadBalancer" se estiver implantando em nuvem e quiser acesso externo
